name: MAJ IPTV AUTO
on:
  schedule:
    - cron: '0 * * * *'  # Se lance toutes les heures
  workflow_dispatch:      # Permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les bibliothèques
        run: pip install requests

      - name: Executer le script de fusion
        run: python fusion_globale.py

      - name: Sauvegarder les changements (EPG et M3U)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add --all
          git commit -m "Mise a jour automatique EPG et M3U" || exit 0
          git push --force origin HEAD:main
          
